/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.chemmastergui;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;

/**
 *
 * @author shram
 */
public class ChemMaster extends javax.swing.JFrame {

    ChemIO chemio = new ChemIO();
    ChemicalListUpdater clu = new ChemicalListUpdater();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ChemMaster.class.getName());

    /**
     * Creates new form ChemMaster
     */
    public ChemMaster() {
        initComponents();
        clu.update(chemsListUI);
        JPopupMenu popupMenu = new JPopupMenu();
        JMenuItem menuItem1 = new JMenuItem("Delete Chemical");
        menuItem1.addActionListener(e -> {
            try {
                chemio.deleteChem(chemsListUI.getSelectedValue());
                clu.update(chemsListUI);
            } catch (Exception e1) {
                System.out.println("Err line 47" + e1);
            }
        });
        popupMenu.add(menuItem1);

        chemsListUI.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                // Check for right-click
                if (SwingUtilities.isRightMouseButton(e)) {
                    // Get the index of the item clicked
                    int index = chemsListUI.locationToIndex(e.getPoint());
                    if (index != -1) { // Ensure an item was clicked
                        chemsListUI.setSelectedIndex(index); // Select the clicked item
                        popupMenu.show(e.getComponent(), e.getX(), e.getY()); // Show the popup
                    }
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        chemsListUI = new javax.swing.JList<>();
        recipeButton = new javax.swing.JButton();
        addChemButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        workspacePanel = new javax.swing.JPanel();
        clearWorkSpaceJButton = new javax.swing.JButton();
        wantedAmountTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ChemMaster4000");

        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });

        chemsListUI.setModel(new DefaultListModel<>());
        jScrollPane1.setViewportView(chemsListUI);

        recipeButton.setText("Show Recipe");
        recipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recipeButtonActionPerformed(evt);
            }
        });

        addChemButton.setText("Add Chemical");
        addChemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addChemButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.setMargin(null);
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        workspacePanel.setBackground(new java.awt.Color(70, 73, 75));
        workspacePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        workspacePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                workspacePanelMouseDragged(evt);
            }
        });
        workspacePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                workspacePanelMousePressed(evt);
            }
        });

        clearWorkSpaceJButton.setText("Clear");
        clearWorkSpaceJButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        clearWorkSpaceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearWorkSpaceJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout workspacePanelLayout = new javax.swing.GroupLayout(workspacePanel);
        workspacePanel.setLayout(workspacePanelLayout);
        workspacePanelLayout.setHorizontalGroup(
            workspacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workspacePanelLayout.createSequentialGroup()
                .addGap(0, 369, Short.MAX_VALUE)
                .addComponent(clearWorkSpaceJButton))
        );
        workspacePanelLayout.setVerticalGroup(
            workspacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workspacePanelLayout.createSequentialGroup()
                .addComponent(clearWorkSpaceJButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        wantedAmountTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wantedAmountTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addChemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(updateButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(wantedAmountTF, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(recipeButton))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(searchField, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(workspacePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wantedAmountTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(recipeButton)
                        .addComponent(updateButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addChemButton)
                .addGap(4, 4, 4))
            .addGroup(layout.createSequentialGroup()
                .addComponent(workspacePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        workspacePanel.getAccessibleContext().setAccessibleName("");
        workspacePanel.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void addChemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addChemButtonActionPerformed
        AddChemical window = new AddChemical();
        window.setVisible(true);

    }//GEN-LAST:event_addChemButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        clu.update(chemsListUI);
    }//GEN-LAST:event_updateButtonActionPerformed

    private void recipeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recipeButtonActionPerformed
        Float wanted;
        try {
            String selected = chemsListUI.getSelectedValue();
            ArrayList<Chemical> chemsList = chemio.readChem();
            for (Chemical chemical : chemsList) {
                if (wantedAmountTF.getText().isEmpty()) {
                    wanted = 1f;
                } else {
                    wanted = Float.valueOf(wantedAmountTF.getText());
                }
                if (selected != null) {
                    if (selected.equals(chemical.getName())) {
                        RecipeComponentPanel rcp = new RecipeComponentPanel(chemical, wanted, workspacePanel, new Point(0,0), new Dimension(0, 0));
                        workspacePanel.add(rcp);
                        workspacePanel.updateUI();

                    }
                }
            }

        } catch (Exception e) {
            System.out.println("Err line 220 " + e);
        }


    }//GEN-LAST:event_recipeButtonActionPerformed

    private void workspacePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workspacePanelMousePressed

    }//GEN-LAST:event_workspacePanelMousePressed

    private void workspacePanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workspacePanelMouseDragged

    }//GEN-LAST:event_workspacePanelMouseDragged

    private void wantedAmountTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wantedAmountTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wantedAmountTFActionPerformed

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        clu.searchInList(searchField.getText(), chemsListUI);
    }//GEN-LAST:event_searchFieldKeyReleased

    private void clearWorkSpaceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearWorkSpaceJButtonActionPerformed
        for (Component c : workspacePanel.getComponents()) {
            if (c instanceof JPanel) {
                workspacePanel.remove(c);
            }
        }
        workspacePanel.updateUI();
    }//GEN-LAST:event_clearWorkSpaceJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
            System.out.println("Err line 272 " + ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ChemMaster().setVisible(true));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addChemButton;
    private javax.swing.JList<String> chemsListUI;
    private javax.swing.JButton clearWorkSpaceJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton recipeButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField wantedAmountTF;
    private javax.swing.JPanel workspacePanel;
    // End of variables declaration//GEN-END:variables

}
